### ISSUE TITLE
Ses window does not close when clicking other menubar item

### ISSUE THREAD

**Issue by lhaeger** [dbilgili/Ses#10]
- Click the Ses icon --> Ses window opens
- Click any other manubar item --> Ses stays visible behind the other item's menu (should become invisible instead) 

<img width="320" alt="NotClosing" src="https://user-images.githubusercontent.com/6388985/101239391-80bac080-36e7-11eb-922a-ad954fe7e6e0.png">

**Comment by dbilgili** [comment]
Hey Lothar,
Thanks for raising that issue. It's fixed now in version [1.0.4](https://github.com/dbilgili/Ses/releases/tag/1.0.4)

**Comment by lhaeger** [comment]
> It's fixed now in version [1.0.4](https://github.com/dbilgili/Ses/releases/tag/1.0.4)
Thanks for the update!
