### ISSUE TITLE
Ability to play URL

### ISSUE THREAD

**Issue by muuuh** [dbilgili/Ses#3]
Hello,

thank you for your app.
Maybe you could also integrate the possibility to play a certain URL in the menu bar.

I'm not sure if it is possible to add it via the sonos npm library
https://github.com/bencevans/node-sonos/issues/422

Thank you

**Comment by dbilgili** [comment]
Hey,
Thanks for the suggestion, but my intention has been to keep it as simple as possible all along, both design and functionality wise.
However, feel free to fork the repo and implement any additional features 👍🏻
