### ISSUE TITLE
it can't be used. I can't uninstall it  and it just like a ghost in book

### ISSUE THREAD

**Issue by syifeng** [dbilgili/Ses#4]
I just delete it in my applications, but it was not be delete actually. When I restart my compute, it just showed again every time. And how could i delete it from my compute

**Comment by dbilgili** [comment]
This is interesting as even if you leave it in the Trash, it should not run at startup.
Make sure it's not in the Trash if that does not help, then open System Preferences and navigate to `Users & Groups > Login Items`. There you should see the application. Try removing it from the list.
